### ISSUE TITLE
preventing users to input html code in forms

### ISSUE THREAD

**Issue by Alirezaies** [Pylons/pyramid_simpleform#38]
as described [here](https://stackoverflow.com/questions/51589312/pyramid-removing-html-tags-from-form-input) does this library can handle this?

**Comment by stevepiercy** [comment]
Please see https://pylonsproject.org/community-support.html

I personally do not know because I don't use this library, I just triage issues. You can write your own regular expression to strip out HTML tags from user input, but it is better to return an error message to the user not to enter HTML characters such as `<` and `>` in the input.
